GET http://localhost:3001/tasks

###
POST http://localhost:3001/tasks
Content-Type: application/json

{
    "title": "test post data-version-045",
    "content": "First test with"
}
###
DELETE http://localhost:3001/tasks/698a15f8bbbe7c4162e3bb

###
GET http://localhost:3001/tasks/698901002adf1040f8a833ff

###
PUT http://localhost:3001/tasks/698901262adf1040f8a83402
Content-Type: application/json

{
    "title": "Setup CI/CD Pipeline - update",
    "content": "Configure GitHub Actions to automatically run unit tests on every push - update"
}